training:
  epochs: 10
  batch_size: 128

model:
  backbone: "resnet50"
  pretrained: true
  num_classes: 100 # TODO

optimizer:
  type: "Adam"           # 支援 "adam", "sgd", "rmsprop"
  learning_rate: 0.0001
  weight_decay: 0
  momentum: 0.9          # 只在 SGD 或 RMSprop 時有效
  epsilon: 1e-8          # 只在 Adam 時有效
