training:
  epochs: 15
  batch_size: 32

model:
  backbone: "resnet50"
  pretrained: true
  inference: ""

optimizer:
  type: "Adam"           # Adam | SGD | RMSprop
  learning_rate: 0.001
  weight_decay: 0.9
  momentum: 0.9          # SGD, RMSprop
  epsilon: 1e-8          # Adam

loss:
  label_smoothing: 0.1
  class_weight: True
  reduction: "none" # TODO

scheduler:
  step_size: 7 
  gamma: 0.1
  