training:
  epochs: 100
  batch_size: 32

model:
  backbone: "resnext101_64x4d"
  pretrained: true
  inference: "next_lr_0.001_batch_32_20250325_194723.pt"

loss:
  label_smoothing: 0.0
  class_weight: False
  reduction: "mean" # TODO
