training:
  epochs: 35
  batch_size: 32

model:
  backbone: "resnext101_64x4d"
  pretrained: true
  inference: "latest_lr_0.005_batch_32_20250325_115246.pt"

optimizer:
  type: "SGD"            # Adam | SGD | RMSprop
  learning_rate: 0.005
  weight_decay: 0
  momentum: 0.9          # SGD, RMSprop
  epsilon: 1e-8          # Adam

loss:
  label_smoothing: 0.0
  class_weight: False
  reduction: "mean" # TODO

scheduler:
  step_size: 2
  gamma: 0.7
